"""Composition library for the pre-registered FX signal survey (#376).

Research-only. Lives in ``backtest/`` and is never imported by
``supabase/functions/``. No LLM, no broker calls, no orders.

**NO FULL-HISTORY EXECUTION HAPPENS HERE.** This module defines and unit-
tests the composition pieces stage 2c's survey run will call
(``prepare_history``, window slicing, metrics, cost/tax matrix,
aggregation, the SPY bar, the §6 survivor evaluator, and the synthetic
smoke fixture) -- every test in ``tests/test_fx_survey.py`` is offline. The
only RUNNABLE entry point that composes all of this end-to-end is
``backtest/run_fx_survey.py --smoke``, which runs on the synthetic fixture
generated by ``make_smoke_fixture`` below, never on real cache data.

Every numeric convention here is pinned by
``docs/research/2026-07-13-forex-4h-strategy-preregistration.md`` (frozen
SHA e409bf8) -- see the docstring of each function for its section
reference.
"""
from __future__ import annotations

import pandas as pd

from backtest import fx_data
from backtest import run_fx_plumbing_check as _plumbing

# spec §5: pre-roll length + first scored calendar year + the ND1 exclusion.
DEFAULT_PRE_ROLL_BARS = 300
DEFAULT_FIRST_TEST_YEAR = 2013
DEFAULT_EXCLUDED_YEARS = (2026,)  # ND1: partial trailing year excluded from scoring


def _build_history(*, fetch: bool, start_year: int, end_year: int) -> tuple:
    """Same manifest-building logic as
    ``run_fx_plumbing_check.build_history`` (cache-first per (year, week),
    concatenated + deduped), but with a caller-supplied ``start_year``
    rather than that module's hardcoded ``START_YEAR`` constant -- lets
    offline tests scope a single small year instead of always sweeping from
    2012."""
    manifest: dict = {}
    frames = []
    for year in range(start_year, end_year + 1):
        manifest[year] = {}
        for week in _plumbing._WEEK_NUMBERS:
            try:
                raw = fx_data.get_week_bytes(year, week, fetch=fetch)
            except (fx_data.WeekNotFoundError, FileNotFoundError):
                manifest[year][week] = None
                continue
            df = fx_data.parse_week_csv(raw)
            manifest[year][week] = len(df)
            frames.append(df)

    if not frames:
        raise SystemExit(
            "BLOCKED: no cached FXCM data found and fetch=False. "
            "Re-run with fetch=True to populate data/fxcm/H1/EURUSD/ (see "
            "backtest/fx_data.py's module docstring for the archive URL "
            "template and re-fetch instructions)."
        )

    history = pd.concat(frames).sort_index()
    history = history[~history.index.duplicated(keep="first")]
    return history, manifest


def prepare_history(
    *, fetch: bool = False, start_year: int = _plumbing.START_YEAR, end_year: int,
) -> dict:
    """Load -> validate (BLOCKED data-kill gate) -> Saturday carve-out ->
    resample to 4h -> drop the in-progress final bar (SUB_PLAN §4).

    Pipeline order (frozen):
      1. Load H1 (cache-first; ``fetch=True`` populates any missing weeks).
      2. Run the #374 validation checks + ``evaluate_blocked_reasons`` --
         the Saturday count is EXCLUDED from this gate (it is about to be
         carved out unconditionally below; a correctly UTC-localized
         archive has zero Saturday bars to begin with -- see
         ``fx_data.check_weekend_bars``'s docstring -- so this exclusion is
         defensive, not a relaxation of a real threshold). All other
         thresholds (missing weeks/rows, coherence, crossed quotes) still
         raise ``SystemExit("BLOCKED: ...")`` if crossed (the #371 "data
         kill" rule, spec §6: "If #371's data/harness package is BLOCKED on
         validation, the survey defined by this document does not run at
         all").
      3. ``fx_data.drop_saturday_bars`` (the count is reported).
      4. Assert ``check_weekend_bars`` now reports 0 Saturday bars.
      5. ``fx_data.resample_to_4h`` then ``fx_data.drop_in_progress_bar``.

    Returns
    -------
    dict with keys ``bars_4h`` (the ready-to-simulate 4h mid/bid/ask OHLC
    frame), ``n_saturday_dropped``, ``resample_report``, ``completeness``,
    ``history_rows``.
    """
    history, manifest = _build_history(fetch=fetch, start_year=start_year, end_year=end_year)

    dupes = fx_data.check_duplicates(history)  # noqa: F841 (reported, not gated here)
    coherence = fx_data.check_ohlc_coherence(history)
    completeness = fx_data.completeness_report(manifest)

    n_rows = max(len(history), 1)
    pct_coherence = coherence["n_coherence_violations"] / n_rows
    pct_crossed_quotes = coherence["n_crossed_quotes"] / n_rows

    # The current/still-publishing end year is excluded from the missing-
    # weeks/rows gate (same convention as run_fx_plumbing_check.main()).
    complete_years = [y for y in completeness if y != end_year]

    blocked_reasons = _plumbing.evaluate_blocked_reasons(
        completeness,
        complete_years=complete_years,
        pct_coherence=pct_coherence,
        pct_crossed_quotes=pct_crossed_quotes,
        n_saturday_bars=0,  # excluded from THIS gate -- carved out unconditionally below
    )
    if blocked_reasons:
        reasons_str = "; ".join(f"{year}: {reason}" for year, reason in blocked_reasons)
        raise SystemExit(f"BLOCKED: data validation thresholds crossed: {reasons_str}")

    history_no_saturdays, n_saturday_dropped = fx_data.drop_saturday_bars(history)
    post_check = fx_data.check_weekend_bars(history_no_saturdays)
    assert post_check["n_saturday_bars"] == 0, (
        "drop_saturday_bars failed to remove all Saturday-UTC rows"
    )

    bars_4h, resample_report = fx_data.resample_to_4h(history_no_saturdays)
    bars_4h = fx_data.drop_in_progress_bar(bars_4h)

    return {
        "bars_4h": bars_4h,
        "n_saturday_dropped": n_saturday_dropped,
        "resample_report": resample_report,
        "completeness": completeness,
        "history_rows": len(history),
    }


def slice_calendar_year_windows(
    index_4h: pd.DatetimeIndex,
    *,
    first_test_year: int = DEFAULT_FIRST_TEST_YEAR,
    pre_roll_bars: int = DEFAULT_PRE_ROLL_BARS,
    excluded_years: tuple = DEFAULT_EXCLUDED_YEARS,
) -> list:
    """Non-overlapping calendar-year test windows over a 4h bar index
    (spec §5).

    - Test window Y = ``[Y-01-01 00:00 UTC, (Y+1)-01-01 00:00 UTC)``.
    - ``first_test_year`` (default 2013): the year BEFORE it (2012) is
      warm-up only and never appears as a window (it can only ever be a
      SOURCE of pre-roll bars for the 2013 window).
    - Pre-roll: exactly ``pre_roll_bars`` bars prepended, found
      POSITIONALLY via ``searchsorted(test_start) - pre_roll_bars``
      (clamped to 0 if the archive doesn't reach back that far).
    - ``excluded_years`` (lead decision ND1, default ``(2026,)``): marked
      ``scored=False`` -- reported as unscored coverage, never fed into any
      survivor statistic -- but the window itself is still generated (a
      partial trailing year is still real coverage to report, just not to
      score on, per the spec §7 freeze clause: results are reported, not
      discarded).
    - Stops once ``test_start`` runs past the last available bar.

    Returns a list of ``{"year", "pre_roll_start", "test_start",
    "test_end", "scored"}`` dicts, oldest first.
    """
    windows: list = []
    if len(index_4h) == 0:
        return windows

    last_ts = index_4h[-1]
    year = first_test_year
    while True:
        test_start = pd.Timestamp(f"{year}-01-01", tz="UTC")
        test_end = pd.Timestamp(f"{year + 1}-01-01", tz="UTC")
        if test_start > last_ts:
            break

        ts_pos = int(index_4h.searchsorted(test_start, side="left"))
        if ts_pos >= len(index_4h):
            break
        pr_pos = max(0, ts_pos - pre_roll_bars)
        pre_roll_start = index_4h[pr_pos]

        windows.append({
            "year": year,
            "pre_roll_start": pre_roll_start,
            "test_start": test_start,
            "test_end": test_end,
            "scored": year not in excluded_years,
        })
        year += 1

    return windows
