"""Composition library for the pre-registered FX signal survey (#376).

Research-only. Lives in ``backtest/`` and is never imported by
``supabase/functions/``. No LLM, no broker calls, no orders.

**NO FULL-HISTORY EXECUTION HAPPENS HERE.** This module defines and unit-
tests the composition pieces stage 2c's survey run will call
(``prepare_history``, window slicing, metrics, cost/tax matrix,
aggregation, the SPY bar, the §6 survivor evaluator, and the synthetic
smoke fixture) -- every test in ``tests/test_fx_survey.py`` is offline. The
only RUNNABLE entry point that composes all of this end-to-end is
``backtest/run_fx_survey.py --smoke``, which runs on the synthetic fixture
generated by ``make_smoke_fixture`` below, never on real cache data.

Every numeric convention here is pinned by
``docs/research/2026-07-13-forex-4h-strategy-preregistration.md`` (frozen
SHA e409bf8) -- see the docstring of each function for its section
reference.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from backtest import fx_costs, fx_data, fx_execution, tax
from backtest import run_fx_plumbing_check as _plumbing

# spec §5: pre-roll length + first scored calendar year + the ND1 exclusion.
DEFAULT_PRE_ROLL_BARS = 300
DEFAULT_FIRST_TEST_YEAR = 2013
DEFAULT_EXCLUDED_YEARS = (2026,)  # ND1: partial trailing year excluded from scoring

# spec §5: forex 24/5 trading-day annualization constant (NOT 252 -- US
# equity/NYSE calendar -- and NOT 365 -- crypto's continuous count).
TRADING_DAYS_PER_YEAR = 260

# spec §5: EURUSD-class pip size, used only by the reconciliation-row helper.
_PIP_SIZE = 0.0001


def _build_history(*, fetch: bool, start_year: int, end_year: int) -> tuple:
    """Same manifest-building logic as
    ``run_fx_plumbing_check.build_history`` (cache-first per (year, week),
    concatenated + deduped), but with a caller-supplied ``start_year``
    rather than that module's hardcoded ``START_YEAR`` constant -- lets
    offline tests scope a single small year instead of always sweeping from
    2012."""
    manifest: dict = {}
    frames = []
    for year in range(start_year, end_year + 1):
        manifest[year] = {}
        for week in _plumbing._WEEK_NUMBERS:
            try:
                raw = fx_data.get_week_bytes(year, week, fetch=fetch)
            except (fx_data.WeekNotFoundError, FileNotFoundError):
                manifest[year][week] = None
                continue
            df = fx_data.parse_week_csv(raw)
            manifest[year][week] = len(df)
            frames.append(df)

    if not frames:
        raise SystemExit(
            "BLOCKED: no cached FXCM data found and fetch=False. "
            "Re-run with fetch=True to populate data/fxcm/H1/EURUSD/ (see "
            "backtest/fx_data.py's module docstring for the archive URL "
            "template and re-fetch instructions)."
        )

    history = pd.concat(frames).sort_index()
    history = history[~history.index.duplicated(keep="first")]
    return history, manifest


def prepare_history(
    *, fetch: bool = False, start_year: int = _plumbing.START_YEAR, end_year: int,
) -> dict:
    """Load -> validate (BLOCKED data-kill gate) -> Saturday carve-out ->
    resample to 4h -> drop the in-progress final bar (SUB_PLAN §4).

    Pipeline order (frozen):
      1. Load H1 (cache-first; ``fetch=True`` populates any missing weeks).
      2. Run the #374 validation checks + ``evaluate_blocked_reasons`` --
         the Saturday count is EXCLUDED from this gate (it is about to be
         carved out unconditionally below; a correctly UTC-localized
         archive has zero Saturday bars to begin with -- see
         ``fx_data.check_weekend_bars``'s docstring -- so this exclusion is
         defensive, not a relaxation of a real threshold). All other
         thresholds (missing weeks/rows, coherence, crossed quotes) still
         raise ``SystemExit("BLOCKED: ...")`` if crossed (the #371 "data
         kill" rule, spec §6: "If #371's data/harness package is BLOCKED on
         validation, the survey defined by this document does not run at
         all").
      3. ``fx_data.drop_saturday_bars`` (the count is reported).
      4. Assert ``check_weekend_bars`` now reports 0 Saturday bars.
      5. ``fx_data.resample_to_4h`` then ``fx_data.drop_in_progress_bar``.

    Returns
    -------
    dict with keys ``bars_4h`` (the ready-to-simulate 4h mid/bid/ask OHLC
    frame), ``n_saturday_dropped``, ``resample_report``, ``completeness``,
    ``history_rows``.
    """
    history, manifest = _build_history(fetch=fetch, start_year=start_year, end_year=end_year)

    dupes = fx_data.check_duplicates(history)  # noqa: F841 (reported, not gated here)
    coherence = fx_data.check_ohlc_coherence(history)
    completeness = fx_data.completeness_report(manifest)

    n_rows = max(len(history), 1)
    pct_coherence = coherence["n_coherence_violations"] / n_rows
    pct_crossed_quotes = coherence["n_crossed_quotes"] / n_rows

    # The current/still-publishing end year is excluded from the missing-
    # weeks/rows gate (same convention as run_fx_plumbing_check.main()).
    complete_years = [y for y in completeness if y != end_year]

    blocked_reasons = _plumbing.evaluate_blocked_reasons(
        completeness,
        complete_years=complete_years,
        pct_coherence=pct_coherence,
        pct_crossed_quotes=pct_crossed_quotes,
        n_saturday_bars=0,  # excluded from THIS gate -- carved out unconditionally below
    )
    if blocked_reasons:
        reasons_str = "; ".join(f"{year}: {reason}" for year, reason in blocked_reasons)
        raise SystemExit(f"BLOCKED: data validation thresholds crossed: {reasons_str}")

    history_no_saturdays, n_saturday_dropped = fx_data.drop_saturday_bars(history)
    post_check = fx_data.check_weekend_bars(history_no_saturdays)
    assert post_check["n_saturday_bars"] == 0, (
        "drop_saturday_bars failed to remove all Saturday-UTC rows"
    )

    bars_4h, resample_report = fx_data.resample_to_4h(history_no_saturdays)
    bars_4h = fx_data.drop_in_progress_bar(bars_4h)

    return {
        "bars_4h": bars_4h,
        "n_saturday_dropped": n_saturday_dropped,
        "resample_report": resample_report,
        "completeness": completeness,
        "history_rows": len(history),
    }


def slice_calendar_year_windows(
    index_4h: pd.DatetimeIndex,
    *,
    first_test_year: int = DEFAULT_FIRST_TEST_YEAR,
    pre_roll_bars: int = DEFAULT_PRE_ROLL_BARS,
    excluded_years: tuple = DEFAULT_EXCLUDED_YEARS,
) -> list:
    """Non-overlapping calendar-year test windows over a 4h bar index
    (spec §5).

    - Test window Y = ``[Y-01-01 00:00 UTC, (Y+1)-01-01 00:00 UTC)``.
    - ``first_test_year`` (default 2013): the year BEFORE it (2012) is
      warm-up only and never appears as a window (it can only ever be a
      SOURCE of pre-roll bars for the 2013 window).
    - Pre-roll: exactly ``pre_roll_bars`` bars prepended, found
      POSITIONALLY via ``searchsorted(test_start) - pre_roll_bars``
      (clamped to 0 if the archive doesn't reach back that far).
    - ``excluded_years`` (lead decision ND1, default ``(2026,)``): marked
      ``scored=False`` -- reported as unscored coverage, never fed into any
      survivor statistic -- but the window itself is still generated (a
      partial trailing year is still real coverage to report, just not to
      score on, per the spec §7 freeze clause: results are reported, not
      discarded).
    - Stops once ``test_start`` runs past the last available bar.

    Returns a list of ``{"year", "pre_roll_start", "test_start",
    "test_end", "scored"}`` dicts, oldest first.
    """
    windows: list = []
    if len(index_4h) == 0:
        return windows

    last_ts = index_4h[-1]
    year = first_test_year
    while True:
        test_start = pd.Timestamp(f"{year}-01-01", tz="UTC")
        test_end = pd.Timestamp(f"{year + 1}-01-01", tz="UTC")
        if test_start > last_ts:
            break

        ts_pos = int(index_4h.searchsorted(test_start, side="left"))
        if ts_pos >= len(index_4h):
            break
        pr_pos = max(0, ts_pos - pre_roll_bars)
        pre_roll_start = index_4h[pr_pos]

        windows.append({
            "year": year,
            "pre_roll_start": pre_roll_start,
            "test_start": test_start,
            "test_end": test_end,
            "scored": year not in excluded_years,
        })
        year += 1

    return windows


# ---------------------------------------------------------------------------
# Metrics (spec §5): total return, maxDD, CAGR, Calmar, Sharpe/vol on
# √260-annualized DAILY-resampled equity, trade count, win rate.
# ---------------------------------------------------------------------------

def compute_window_metrics(equity_test: pd.Series, trades: list) -> dict:
    """Per-window metrics on a (pre-tax OR after-tax) equity slice.

    Sharpe/vol are computed on the equity resampled to DAILY (via
    ``fx_execution.equity_to_daily``) and annualized with **√260** (spec
    §5 -- the forex 24/5 trading-day count, not 252/365). total_return,
    max_drawdown, CAGR, and Calmar are computed directly on
    ``equity_test`` at its native cadence (cadence-agnostic metrics; CAGR
    uses the slice's CALENDAR span, matching
    ``walkforward._compute_window_metrics``'s own convention, adopted by
    reference per SUB_PLAN §3 pin (d)).

    Calmar is NaN when max_drawdown == 0 (no drawdown to divide by --
    SUB_PLAN §3 pin (e); aggregation skips NaN Calmar windows from the
    median but counts them).

    win_rate (SUB_PLAN §3 pin (c)): fraction of ``trades`` with ``pnl`` >
    0; NaN when there are zero trades (undefined, not zero -- a
    trade-free window says nothing about win rate one way or the other).
    """
    if len(equity_test) == 0:
        return {
            "total_return": 0.0, "max_drawdown": 0.0, "cagr": 0.0,
            "calmar": float("nan"), "sharpe": 0.0, "annualized_vol": 0.0,
            "trade_count": 0, "win_rate": float("nan"),
        }

    total_return = float(equity_test.iloc[-1] / equity_test.iloc[0] - 1.0)
    rolling_max = equity_test.cummax()
    max_dd = float(((equity_test - rolling_max) / rolling_max).min())

    span_days = (equity_test.index[-1] - equity_test.index[0]).days
    span_years = span_days / 365.25
    if span_years > 0:
        cagr = float((1.0 + total_return) ** (1.0 / span_years) - 1.0)
    else:
        cagr = 0.0

    calmar = float(cagr / abs(max_dd)) if max_dd != 0 else float("nan")

    daily = fx_execution.equity_to_daily(equity_test)
    daily_rets = daily.pct_change().dropna()
    if len(daily_rets) >= 2:
        mean_r = float(daily_rets.mean())
        std_r = float(daily_rets.std(ddof=1))
        sharpe = (mean_r / std_r * (TRADING_DAYS_PER_YEAR ** 0.5)) if std_r > 0 else 0.0
        annualized_vol = std_r * (TRADING_DAYS_PER_YEAR ** 0.5)
    else:
        sharpe = 0.0
        annualized_vol = 0.0

    trade_count = len(trades)
    if trade_count > 0:
        n_wins = sum(1 for t in trades if t.get("pnl", 0.0) > 0)
        win_rate = n_wins / trade_count
    else:
        win_rate = float("nan")

    return {
        "total_return": total_return,
        "max_drawdown": max_dd,
        "cagr": cagr,
        "calmar": calmar,
        "sharpe": sharpe,
        "annualized_vol": annualized_vol,
        "trade_count": trade_count,
        "win_rate": win_rate,
    }


def compute_after_tax_metrics(equity_test: pd.Series, trades: list, *, mode: str) -> dict:
    """Apply one of the two pinned tax modes (spec §5) to ``equity_test``,
    then compute the same metrics ``compute_window_metrics`` returns.

    ``mode``:
      - ``"annual_netting"`` -- ``tax.apply_annual_netting_tax`` (PRIMARY,
        German calendar-year netting).
      - ``"de_sensitivity"`` -- ``tax.apply_tax_to_ledger(jurisdiction="DE")``
        (the existing no-loss-credit deduct-at-exit model, SENSITIVITY
        only -- never a survivor basis, spec §5).
    """
    if mode == "annual_netting":
        after_tax_eq = tax.apply_annual_netting_tax(trades, equity_test)
    elif mode == "de_sensitivity":
        after_tax_eq = tax.apply_tax_to_ledger(trades, equity_test, jurisdiction="DE")
    else:
        raise ValueError(f"unknown tax mode {mode!r}; expected 'annual_netting' or 'de_sensitivity'")
    return compute_window_metrics(after_tax_eq, trades)


# ---------------------------------------------------------------------------
# Cost matrix (spec §5): 4 venues × {base, pessimistic} + the FXCM-spread
# reconciliation row (SUB_PLAN §3 interpretive pin (f)).
# ---------------------------------------------------------------------------

def reconciliation_cost_rt(median_spread_pips: float, *, ref_price: float = 1.10) -> float:
    """Convert a median MEASURED FXCM spread (pips) into a round-trip
    ``cost_rt`` (fraction of notional) -- one round trip pays the spread
    once (buy at ask, sell at bid). 1 pip = 0.0001 for a EURUSD-class pair
    (``fx_data.empirical_spread_pips``'s own convention).

    This is a RECONCILIATION row against the published/fetched venue
    presets below, never a fifth cost preset or a survivor basis in its own
    right (spec §5)."""
    return (median_spread_pips * _PIP_SIZE) / ref_price


def cost_rows(*, measured_spread_pips: "float | None" = None) -> list:
    """Every row of the spec §5 cost matrix: all 4 ``fx_costs.PRESETS`` ×
    {base, pessimistic} (8 rows; co-primary = XTB CFD base AND CME 6E base,
    spec §5 lead decision #6 -- the rest are sensitivity), plus one
    optional labeled reconciliation row (a 9th row) when
    ``measured_spread_pips`` is given.

    Each row: ``{label, venue_key, cost_mode, cost_rt, overnight,
    is_co_primary}``. ``overnight`` mirrors
    ``run_fx_plumbing_check.main()``'s own wiring exactly (``None`` for
    futures presets -- no daily rollover charge; a ``{1: ..., -1: ...}``
    dict of fractional per-night rates for spot/CFD presets).
    """
    rows: list = []
    for key, preset in fx_costs.PRESETS.items():
        for mode, bp in (("base", preset.base_bp), ("pessimistic", preset.pessimistic_bp)):
            overnight = None
            if preset.has_overnight:
                overnight = {
                    1: fx_costs.overnight_bp_for(preset, "long") / 10_000.0,
                    -1: fx_costs.overnight_bp_for(preset, "short") / 10_000.0,
                }
            rows.append({
                "label": f"{preset.name} ({mode})",
                "venue_key": key,
                "cost_mode": mode,
                "cost_rt": bp / 10_000.0,
                "overnight": overnight,
                "is_co_primary": key in ("xtb", "6e") and mode == "base",
            })

    if measured_spread_pips is not None:
        rows.append({
            "label": "FXCM measured-spread reconciliation",
            "venue_key": "fxcm_reconciliation",
            "cost_mode": "reconciliation",
            "cost_rt": reconciliation_cost_rt(measured_spread_pips),
            "overnight": None,
            "is_co_primary": False,
        })

    return rows


# ---------------------------------------------------------------------------
# Aggregation: median/worst-window across a cell's scored windows, with the
# NaN-Calmar and baseline-4-degenerate-window conventions (spec §5/§6).
# ---------------------------------------------------------------------------

def aggregate_metric_across_windows(window_metrics: list) -> dict:
    """Aggregate a cell's per-window metrics (SCORED windows only -- the
    caller filters out ``scored=False`` windows, e.g. the ND1-excluded
    partial 2026 year) into the per-cell summary the §6 survivor evaluator
    consumes.

    - ``median_calmar``: median of the NON-NaN calmar values (SUB_PLAN §3
      pin (e)) -- NaN if every window's calmar is NaN.
    - ``n_nan_calmar_windows``: count of windows skipped from that median.
    - ``median_total_return``, ``worst_window_total_return`` (+ its
      ``worst_window_label``): computed over ALL windows (total_return is
      always defined, never NaN).
    - ``n_windows``: total scored windows fed in.

    Each element of ``window_metrics`` must carry at least ``"year"``,
    ``"total_return"``, ``"calmar"``.
    """
    calmars = [m["calmar"] for m in window_metrics]
    n_nan = sum(1 for c in calmars if pd.isna(c))
    valid_calmars = [c for c in calmars if not pd.isna(c)]
    median_calmar = float(np.median(valid_calmars)) if valid_calmars else float("nan")

    returns = [m["total_return"] for m in window_metrics]
    median_return = float(np.median(returns)) if returns else float("nan")

    if returns:
        worst_pos = int(np.argmin(returns))
        worst_return = float(returns[worst_pos])
        worst_label = window_metrics[worst_pos]["year"]
    else:
        worst_return = float("nan")
        worst_label = None

    return {
        "median_calmar": median_calmar,
        "n_nan_calmar_windows": n_nan,
        "median_total_return": median_return,
        "worst_window_total_return": worst_return,
        "worst_window_label": worst_label,
        "n_windows": len(window_metrics),
    }


def apply_baseline4_degenerate_convention(window_metrics: list) -> list:
    """Baseline-4 (200-SMA regime) degenerate-window convention (spec §6):
    in any window where baseline 4 is flat for the WHOLE window (zero
    trades, an otherwise-undefined 0/0 Calmar ratio), that window's return
    -- AND its Calmar -- are treated as EXACTLY 0 for the comparison,
    mirroring baseline 1's "median return > 0" convention rather than
    discarding the window or leaving it NaN (which would otherwise get
    silently skipped by ``aggregate_metric_across_windows``'s NaN-Calmar
    handling -- the wrong outcome here, since this is a "the baseline did
    nothing" result, not a "the baseline is undefined" one).

    Pure function; returns a NEW list (does not mutate the input)."""
    adjusted = []
    for m in window_metrics:
        if m.get("trade_count", 0) == 0:
            new_m = dict(m)
            new_m["total_return"] = 0.0
            new_m["calmar"] = 0.0
            adjusted.append(new_m)
        else:
            adjusted.append(dict(m))
    return adjusted
