"""Composition library for the pre-registered FX signal survey (#376).

Research-only. Lives in ``backtest/`` and is never imported by
``supabase/functions/``. No LLM, no broker calls, no orders.

**NO FULL-HISTORY EXECUTION HAPPENS HERE.** This module defines and unit-
tests the composition pieces stage 2c's survey run will call
(``prepare_history``, window slicing, metrics, cost/tax matrix,
aggregation, the SPY bar, the §6 survivor evaluator, and the synthetic
smoke fixture) -- every test in ``tests/test_fx_survey.py`` is offline. The
only RUNNABLE entry point that composes all of this end-to-end is
``backtest/run_fx_survey.py --smoke``, which runs on the synthetic fixture
generated by ``make_smoke_fixture`` below, never on real cache data.

Every numeric convention here is pinned by
``docs/research/2026-07-13-forex-4h-strategy-preregistration.md`` (frozen
SHA e409bf8) -- see the docstring of each function for its section
reference.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from backtest import baselines as _equity_baselines
from backtest import fx_baselines, fx_costs, fx_data, fx_execution, fx_signals, regime, tax
from backtest import run_fx_plumbing_check as _plumbing

# spec §5: co-primary venues -- a survivor must clear the bar on BOTH.
CO_PRIMARY_VENUES = ("xtb_base", "6e_base")

# spec §5: pre-roll length + first scored calendar year + the ND1 exclusion.
DEFAULT_PRE_ROLL_BARS = 300
DEFAULT_FIRST_TEST_YEAR = 2013
DEFAULT_EXCLUDED_YEARS = (2026,)  # ND1: partial trailing year excluded from scoring

# spec §5: forex 24/5 trading-day annualization constant (NOT 252 -- US
# equity/NYSE calendar -- and NOT 365 -- crypto's continuous count).
TRADING_DAYS_PER_YEAR = 260

# spec §5: EURUSD-class pip size, used only by the reconciliation-row helper.
_PIP_SIZE = 0.0001


def _build_history(*, fetch: bool, start_year: int, end_year: int) -> tuple:
    """Same manifest-building logic as
    ``run_fx_plumbing_check.build_history`` (cache-first per (year, week),
    concatenated + deduped), but with a caller-supplied ``start_year``
    rather than that module's hardcoded ``START_YEAR`` constant -- lets
    offline tests scope a single small year instead of always sweeping from
    2012."""
    manifest: dict = {}
    frames = []
    for year in range(start_year, end_year + 1):
        manifest[year] = {}
        for week in _plumbing._WEEK_NUMBERS:
            try:
                raw = fx_data.get_week_bytes(year, week, fetch=fetch)
            except (fx_data.WeekNotFoundError, FileNotFoundError):
                manifest[year][week] = None
                continue
            df = fx_data.parse_week_csv(raw)
            manifest[year][week] = len(df)
            frames.append(df)

    if not frames:
        raise SystemExit(
            "BLOCKED: no cached FXCM data found and fetch=False. "
            "Re-run with fetch=True to populate data/fxcm/H1/EURUSD/ (see "
            "backtest/fx_data.py's module docstring for the archive URL "
            "template and re-fetch instructions)."
        )

    history = pd.concat(frames).sort_index()
    history = history[~history.index.duplicated(keep="first")]
    return history, manifest


def prepare_history(
    *, fetch: bool = False, start_year: int = _plumbing.START_YEAR, end_year: int,
) -> dict:
    """Load -> validate (BLOCKED data-kill gate) -> Saturday carve-out ->
    resample to 4h -> drop the in-progress final bar (SUB_PLAN §4).

    Pipeline order (frozen):
      1. Load H1 (cache-first; ``fetch=True`` populates any missing weeks).
      2. Run the #374 validation checks + ``evaluate_blocked_reasons`` --
         the Saturday count is EXCLUDED from this gate (it is about to be
         carved out unconditionally below; a correctly UTC-localized
         archive has zero Saturday bars to begin with -- see
         ``fx_data.check_weekend_bars``'s docstring -- so this exclusion is
         defensive, not a relaxation of a real threshold). All other
         thresholds (missing weeks/rows, coherence, crossed quotes) still
         raise ``SystemExit("BLOCKED: ...")`` if crossed (the #371 "data
         kill" rule, spec §6: "If #371's data/harness package is BLOCKED on
         validation, the survey defined by this document does not run at
         all").
      3. ``fx_data.drop_saturday_bars`` (the count is reported).
      4. Assert ``check_weekend_bars`` now reports 0 Saturday bars.
      5. ``fx_data.resample_to_4h`` then ``fx_data.drop_in_progress_bar``.

    Returns
    -------
    dict with keys ``bars_4h`` (the ready-to-simulate 4h mid/bid/ask OHLC
    frame), ``n_saturday_dropped``, ``resample_report``, ``completeness``,
    ``history_rows``, ``n_duplicates`` (duplicate H1 timestamps found --
    reported for visibility; not itself a BLOCKED threshold in this
    function, per ``fx_data.check_duplicates``).
    """
    history, manifest = _build_history(fetch=fetch, start_year=start_year, end_year=end_year)

    dupes = fx_data.check_duplicates(history)  # reported below, not gated here
    coherence = fx_data.check_ohlc_coherence(history)
    completeness = fx_data.completeness_report(manifest)

    n_rows = max(len(history), 1)
    pct_coherence = coherence["n_coherence_violations"] / n_rows
    pct_crossed_quotes = coherence["n_crossed_quotes"] / n_rows

    # The current/still-publishing end year is excluded from the missing-
    # weeks/rows gate (same convention as run_fx_plumbing_check.main()).
    complete_years = [y for y in completeness if y != end_year]

    blocked_reasons = _plumbing.evaluate_blocked_reasons(
        completeness,
        complete_years=complete_years,
        pct_coherence=pct_coherence,
        pct_crossed_quotes=pct_crossed_quotes,
        n_saturday_bars=0,  # excluded from THIS gate -- carved out unconditionally below
    )
    if blocked_reasons:
        reasons_str = "; ".join(f"{year}: {reason}" for year, reason in blocked_reasons)
        raise SystemExit(f"BLOCKED: data validation thresholds crossed: {reasons_str}")

    history_no_saturdays, n_saturday_dropped = fx_data.drop_saturday_bars(history)
    post_check = fx_data.check_weekend_bars(history_no_saturdays)
    assert post_check["n_saturday_bars"] == 0, (
        "drop_saturday_bars failed to remove all Saturday-UTC rows"
    )

    bars_4h, resample_report = fx_data.resample_to_4h(history_no_saturdays)
    bars_4h = fx_data.drop_in_progress_bar(bars_4h)

    return {
        "bars_4h": bars_4h,
        "n_saturday_dropped": n_saturday_dropped,
        "resample_report": resample_report,
        "completeness": completeness,
        "history_rows": len(history),
        "n_duplicates": dupes["n_duplicates"],
    }


def slice_calendar_year_windows(
    index_4h: pd.DatetimeIndex,
    *,
    first_test_year: int = DEFAULT_FIRST_TEST_YEAR,
    pre_roll_bars: int = DEFAULT_PRE_ROLL_BARS,
    excluded_years: tuple = DEFAULT_EXCLUDED_YEARS,
) -> list:
    """Non-overlapping calendar-year test windows over a 4h bar index
    (spec §5).

    - Test window Y = ``[Y-01-01 00:00 UTC, (Y+1)-01-01 00:00 UTC)``.
    - ``first_test_year`` (default 2013): the year BEFORE it (2012) is
      warm-up only and never appears as a window (it can only ever be a
      SOURCE of pre-roll bars for the 2013 window).
    - Pre-roll: exactly ``pre_roll_bars`` bars prepended, found
      POSITIONALLY via ``searchsorted(test_start) - pre_roll_bars``
      (clamped to 0 if the archive doesn't reach back that far).
    - ``excluded_years`` (lead decision ND1, default ``(2026,)``): marked
      ``scored=False`` -- reported as unscored coverage, never fed into any
      survivor statistic -- but the window itself is still generated (a
      partial trailing year is still real coverage to report, just not to
      score on, per the spec §7 freeze clause: results are reported, not
      discarded).
    - Stops once ``test_start`` runs past the last available bar.

    Returns a list of ``{"year", "pre_roll_start", "test_start",
    "test_end", "scored"}`` dicts, oldest first.
    """
    windows: list = []
    if len(index_4h) == 0:
        return windows

    last_ts = index_4h[-1]
    year = first_test_year
    while True:
        test_start = pd.Timestamp(f"{year}-01-01", tz="UTC")
        test_end = pd.Timestamp(f"{year + 1}-01-01", tz="UTC")
        if test_start > last_ts:
            break

        ts_pos = int(index_4h.searchsorted(test_start, side="left"))
        if ts_pos >= len(index_4h):
            break
        pr_pos = max(0, ts_pos - pre_roll_bars)
        pre_roll_start = index_4h[pr_pos]

        windows.append({
            "year": year,
            "pre_roll_start": pre_roll_start,
            "test_start": test_start,
            "test_end": test_end,
            "scored": year not in excluded_years,
        })
        year += 1

    return windows


# ---------------------------------------------------------------------------
# Metrics (spec §5): total return, maxDD, CAGR, Calmar, Sharpe/vol on
# √260-annualized DAILY-resampled equity, trade count, win rate.
# ---------------------------------------------------------------------------

def compute_window_metrics(equity_test: pd.Series, trades: list) -> dict:
    """Per-window metrics on a (pre-tax OR after-tax) equity slice.

    Sharpe/vol are computed on the equity resampled to DAILY (via
    ``fx_execution.equity_to_daily``) and annualized with **√260** (spec
    §5 -- the forex 24/5 trading-day count, not 252/365). total_return,
    max_drawdown, CAGR, and Calmar are computed directly on
    ``equity_test`` at its native cadence (cadence-agnostic metrics; CAGR
    uses the slice's CALENDAR span, matching
    ``walkforward._compute_window_metrics``'s own convention, adopted by
    reference per SUB_PLAN §3 pin (d)).

    Calmar is NaN when max_drawdown == 0 (no drawdown to divide by --
    SUB_PLAN §3 pin (e); aggregation skips NaN Calmar windows from the
    median but counts them).

    win_rate (SUB_PLAN §3 pin (c)): fraction of ``trades`` with ``pnl`` >
    0; NaN when there are zero trades (undefined, not zero -- a
    trade-free window says nothing about win rate one way or the other).
    """
    if len(equity_test) == 0:
        return {
            "total_return": 0.0, "max_drawdown": 0.0, "cagr": 0.0,
            "calmar": float("nan"), "sharpe": 0.0, "annualized_vol": 0.0,
            "trade_count": 0, "win_rate": float("nan"),
        }

    total_return = float(equity_test.iloc[-1] / equity_test.iloc[0] - 1.0)
    rolling_max = equity_test.cummax()
    max_dd = float(((equity_test - rolling_max) / rolling_max).min())

    span_days = (equity_test.index[-1] - equity_test.index[0]).days
    span_years = span_days / 365.25
    if span_years > 0:
        cagr = float((1.0 + total_return) ** (1.0 / span_years) - 1.0)
    else:
        cagr = 0.0

    calmar = float(cagr / abs(max_dd)) if max_dd != 0 else float("nan")

    daily = fx_execution.equity_to_daily(equity_test)
    daily_rets = daily.pct_change().dropna()
    if len(daily_rets) >= 2:
        mean_r = float(daily_rets.mean())
        std_r = float(daily_rets.std(ddof=1))
        sharpe = (mean_r / std_r * (TRADING_DAYS_PER_YEAR ** 0.5)) if std_r > 0 else 0.0
        annualized_vol = std_r * (TRADING_DAYS_PER_YEAR ** 0.5)
    else:
        sharpe = 0.0
        annualized_vol = 0.0

    trade_count = len(trades)
    if trade_count > 0:
        n_wins = sum(1 for t in trades if t.get("pnl", 0.0) > 0)
        win_rate = n_wins / trade_count
    else:
        win_rate = float("nan")

    return {
        "total_return": total_return,
        "max_drawdown": max_dd,
        "cagr": cagr,
        "calmar": calmar,
        "sharpe": sharpe,
        "annualized_vol": annualized_vol,
        "trade_count": trade_count,
        "win_rate": win_rate,
    }


def compute_after_tax_metrics(equity_test: pd.Series, trades: list, *, mode: str) -> dict:
    """Apply one of the two pinned tax modes (spec §5) to ``equity_test``,
    then compute the same metrics ``compute_window_metrics`` returns.

    ``mode``:
      - ``"annual_netting"`` -- ``tax.apply_annual_netting_tax`` (PRIMARY,
        German calendar-year netting).
      - ``"de_sensitivity"`` -- ``tax.apply_tax_to_ledger(jurisdiction="DE")``
        (the existing no-loss-credit deduct-at-exit model, SENSITIVITY
        only -- never a survivor basis, spec §5).
    """
    if mode == "annual_netting":
        after_tax_eq = tax.apply_annual_netting_tax(trades, equity_test)
    elif mode == "de_sensitivity":
        after_tax_eq = tax.apply_tax_to_ledger(trades, equity_test, jurisdiction="DE")
    else:
        raise ValueError(f"unknown tax mode {mode!r}; expected 'annual_netting' or 'de_sensitivity'")
    return compute_window_metrics(after_tax_eq, trades)


# ---------------------------------------------------------------------------
# Cost matrix (spec §5): 4 venues × {base, pessimistic} + the FXCM-spread
# reconciliation row (SUB_PLAN §3 interpretive pin (f)).
# ---------------------------------------------------------------------------

def reconciliation_cost_rt(median_spread_pips: float, *, ref_price: float = 1.10) -> float:
    """Convert a median MEASURED FXCM spread (pips) into a round-trip
    ``cost_rt`` (fraction of notional) -- one round trip pays the spread
    once (buy at ask, sell at bid). 1 pip = 0.0001 for a EURUSD-class pair
    (``fx_data.empirical_spread_pips``'s own convention).

    This is a RECONCILIATION row against the published/fetched venue
    presets below, never a fifth cost preset or a survivor basis in its own
    right (spec §5)."""
    return (median_spread_pips * _PIP_SIZE) / ref_price


def cost_rows(*, measured_spread_pips: "float | None" = None) -> list:
    """Every row of the spec §5 cost matrix: all 4 ``fx_costs.PRESETS`` ×
    {base, pessimistic} (8 rows; co-primary = XTB CFD base AND CME 6E base,
    spec §5 lead decision #6 -- the rest are sensitivity), plus one
    optional labeled reconciliation row (a 9th row) when
    ``measured_spread_pips`` is given.

    Each row: ``{label, venue_key, cost_mode, cost_rt, overnight,
    is_co_primary}``. ``overnight`` mirrors
    ``run_fx_plumbing_check.main()``'s own wiring exactly (``None`` for
    futures presets -- no daily rollover charge; a ``{1: ..., -1: ...}``
    dict of fractional per-night rates for spot/CFD presets).
    """
    rows: list = []
    for key, preset in fx_costs.PRESETS.items():
        for mode, bp in (("base", preset.base_bp), ("pessimistic", preset.pessimistic_bp)):
            overnight = None
            if preset.has_overnight:
                overnight = {
                    1: fx_costs.overnight_bp_for(preset, "long") / 10_000.0,
                    -1: fx_costs.overnight_bp_for(preset, "short") / 10_000.0,
                }
            rows.append({
                "label": f"{preset.name} ({mode})",
                "venue_key": key,
                "cost_mode": mode,
                "cost_rt": bp / 10_000.0,
                "overnight": overnight,
                "is_co_primary": key in ("xtb", "6e") and mode == "base",
            })

    if measured_spread_pips is not None:
        rows.append({
            "label": "FXCM measured-spread reconciliation",
            "venue_key": "fxcm_reconciliation",
            "cost_mode": "reconciliation",
            "cost_rt": reconciliation_cost_rt(measured_spread_pips),
            "overnight": None,
            "is_co_primary": False,
        })

    return rows


# ---------------------------------------------------------------------------
# Aggregation: median/worst-window across a cell's scored windows, with the
# NaN-Calmar and baseline-4-degenerate-window conventions (spec §5/§6).
# ---------------------------------------------------------------------------

# Every metric `compute_window_metrics` returns -- the summary carries a
# median of EACH of these (SUB_PLAN §6: "full per-window rows plus a
# summary -- median across windows of EACH metric"), not just calmar and
# total_return.
METRIC_KEYS = (
    "total_return", "max_drawdown", "cagr", "calmar",
    "sharpe", "annualized_vol", "trade_count", "win_rate",
)


def _median_skip_nan(values: list) -> float:
    """Median of the non-NaN values in ``values``; NaN if the list is empty
    or every value is NaN. Plain-Python filtering (not ``np.nanmedian``) so
    an all-NaN metric never raises a numpy RuntimeWarning."""
    non_nan = [v for v in values if not pd.isna(v)]
    return float(np.median(non_nan)) if non_nan else float("nan")


def aggregate_metric_across_windows(window_metrics: list) -> dict:
    """Aggregate a cell's per-window metrics (SCORED, non-skipped windows
    only -- the caller filters out ``scored=False`` windows, e.g. the
    ND1-excluded partial 2026 year, and any window recorded as skipped for
    insufficient bars) into the per-cell summary the §6 survivor evaluator
    consumes.

    - ``median_<key>`` for every key in ``METRIC_KEYS``: median of the
      NON-NaN values (SUB_PLAN §3 pin (e); a metric missing from an
      element -- e.g. a minimal test fixture -- contributes NaN via
      ``dict.get``, never a ``KeyError``) -- NaN if every window's value
      for that metric is NaN.
    - ``n_nan_calmar_windows``: count of windows skipped from the Calmar
      median specifically (the one metric SUB_PLAN §3 calls out by name).
    - ``worst_window_total_return`` (+ its ``worst_window_label``):
      computed over ALL windows fed in (total_return is always defined,
      never NaN).
    - ``n_windows``: total scored, non-skipped windows fed in.
    """
    if not window_metrics:
        summary = {f"median_{key}": float("nan") for key in METRIC_KEYS}
        summary.update({
            "worst_window_total_return": float("nan"),
            "worst_window_label": None,
            "n_windows": 0,
            "n_nan_calmar_windows": 0,
        })
        return summary

    summary = {
        f"median_{key}": _median_skip_nan([m.get(key, float("nan")) for m in window_metrics])
        for key in METRIC_KEYS
    }

    calmars = [m.get("calmar", float("nan")) for m in window_metrics]
    n_nan_calmar = sum(1 for c in calmars if pd.isna(c))

    returns = [m["total_return"] for m in window_metrics]
    worst_pos = int(np.argmin(returns))
    worst_return = float(returns[worst_pos])
    worst_label = window_metrics[worst_pos]["year"]

    summary.update({
        "worst_window_total_return": worst_return,
        "worst_window_label": worst_label,
        "n_windows": len(window_metrics),
        "n_nan_calmar_windows": n_nan_calmar,
    })
    return summary


def apply_baseline4_degenerate_convention(window_metrics: list) -> list:
    """Baseline-4 (200-SMA regime) degenerate-window convention (spec §6):
    in any window where baseline 4 is flat for the WHOLE window (zero
    trades, an otherwise-undefined 0/0 Calmar ratio), that window's return
    -- AND its Calmar -- are treated as EXACTLY 0 for the comparison,
    mirroring baseline 1's "median return > 0" convention rather than
    discarding the window or leaving it NaN (which would otherwise get
    silently skipped by ``aggregate_metric_across_windows``'s NaN-Calmar
    handling -- the wrong outcome here, since this is a "the baseline did
    nothing" result, not a "the baseline is undefined" one).

    Pure function; returns a NEW list (does not mutate the input)."""
    adjusted = []
    for m in window_metrics:
        if m.get("trade_count", 0) == 0:
            new_m = dict(m)
            new_m["total_return"] = 0.0
            new_m["calmar"] = 0.0
            adjusted.append(new_m)
        else:
            adjusted.append(dict(m))
    return adjusted


# ---------------------------------------------------------------------------
# SPY bar (spec §5, "the bar", inherited from #255 §2/§5): SPY buy-and-hold
# after-tax Calmar on the SAME calendar test windows as the FX survey.
# Smoke-only execution (lead decision ND2) -- offline-tested via a
# monkeypatchable ``_fetch_spy`` seam, per the ``walkforward.py`` precedent.
# ---------------------------------------------------------------------------

def _fetch_spy(ticker: str, start, end) -> pd.DataFrame:
    """Network seam -- yfinance. The ONLY function that touches the network
    for the SPY bar. Patched by every offline test; never called by
    anything in this package except ``run_fx_survey.py --smoke``, and even
    there only against the synthetic SPY frame the smoke fixture builds (a
    monkeypatched ``fetch=`` argument, not this function itself)."""
    import yfinance as yf

    df = yf.download(ticker, start=start, end=end, auto_adjust=True, progress=False)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    return df[["Open", "Close"]].dropna()


def compute_spy_windows(*, calendar_windows: list, ticker: str = "SPY", fetch=None) -> list:
    """SPY buy-and-hold, after-tax (German annual-netting, PRIMARY mode),
    on the same calendar windows the FX survey uses (spec §5's "the bar").

    Fetches ONCE for the whole span (min pre-roll start -> max test end),
    reuses ``regime.py``'s existing ``SLIPPAGE_BPS``/``COMMISSION_BPS``
    frictions and ``simulate_from_signal`` + ``baselines.buy_and_hold_signal``
    (an all-True signal -- fee-adjusted buy-and-hold), same Trap-A
    test-sub-window-only metrics convention as ``walkforward.py``.

    Returns a list of per-window metrics dicts (``{"year", "scored",
    **compute_after_tax_metrics(...)}``) -- windows with fewer than 2 test
    bars are skipped (insufficient data for a return).
    """
    fetch_fn = fetch or _fetch_spy
    if not calendar_windows:
        return []

    span_start = min(w["pre_roll_start"] for w in calendar_windows)
    span_end = max(w["test_end"] for w in calendar_windows)
    full = fetch_fn(ticker, pd.Timestamp(span_start).date(), pd.Timestamp(span_end).date())

    rows: list = []
    for w in calendar_windows:
        # SPY's daily calendar is tz-naive (yfinance convention); the FX
        # survey's own windows are tz-aware UTC -- strip tz for this
        # comparison only, since a calendar DAY boundary is what matters
        # here, not a specific UTC instant.
        pre_roll_start = pd.Timestamp(w["pre_roll_start"]).tz_localize(None)
        test_start = pd.Timestamp(w["test_start"]).tz_localize(None)
        test_end = pd.Timestamp(w["test_end"]).tz_localize(None)

        mask = (full.index >= pre_roll_start) & (full.index <= test_end)
        window_df = full.loc[mask]
        if len(window_df) < 2:
            continue
        sig = _equity_baselines.buy_and_hold_signal(window_df["Close"])
        sim = regime.simulate_from_signal(
            vehicle_df=window_df, is_bullish_close_t=sig,
            slippage_bps=regime.SLIPPAGE_BPS, commission_bps=regime.COMMISSION_BPS,
        )
        eq_full = sim["equity_curve"]
        test_mask = (eq_full.index >= test_start) & (eq_full.index < test_end)
        eq_test = eq_full.loc[test_mask]
        if len(eq_test) < 2:
            continue
        test_trades = [
            t for t in sim["trades"]
            if t["exit_date"] >= test_start and t["exit_date"] < test_end
        ]
        after_tax = compute_after_tax_metrics(eq_test, test_trades, mode="annual_netting")
        rows.append({"year": w["year"], "scored": w.get("scored", True), **after_tax})

    return rows


# ---------------------------------------------------------------------------
# §6 survivor evaluator -- pure function over already-computed aggregates.
# Truth-table-tested; executed only in smoke mode (lead decision ND2).
# ---------------------------------------------------------------------------

def evaluate_survivor(
    *,
    cell_agg: dict,
    baseline_aggs: dict,
    spy_median_calmar: float,
    co_primary_venues: tuple = CO_PRIMARY_VENUES,
) -> dict:
    """A single (family, shape, R) cell is a survivor iff, at BOTH
    co-primary venues and under the primary tax mode (both already baked
    into ``cell_agg``/``baseline_aggs`` by the caller), all three spec §6
    conditions hold simultaneously.

    Parameters
    ----------
    cell_agg:
        ``{venue: {"median_calmar", "median_total_return",
        "worst_window_total_return"}}`` for the candidate cell, one entry
        per venue in ``co_primary_venues``.
    baseline_aggs:
        ``{"buy_and_hold": {venue: {...}}, "persistence": {venue: {...}},
        "sma200_regime": {venue: {...}}}`` -- baseline 1 (always-flat) is
        NOT here; its criterion is applied directly to the candidate's own
        ``median_total_return`` (condition 2's first clause, below).
    spy_median_calmar:
        SPY buy-and-hold's median-window after-tax Calmar (single value --
        SPY has its own frictions, not an FX venue cost).

    Returns ``{"is_survivor", "condition_1", "condition_2", "condition_3"}``.
    NaN comparisons evaluate False in Python/numpy, so a NaN
    ``median_calmar`` deterministically fails conditions 1/2 without any
    special-casing (SUB_PLAN §3 pin (e)).
    """
    condition_1 = all(
        cell_agg[v]["median_calmar"] > spy_median_calmar for v in co_primary_venues
    )

    beats_always_flat = all(
        cell_agg[v]["median_total_return"] > 0 for v in co_primary_venues
    )
    beats_other_baselines = all(
        cell_agg[v]["median_calmar"] > baseline_aggs[b][v]["median_calmar"]
        for b in ("buy_and_hold", "persistence", "sma200_regime")
        for v in co_primary_venues
    )
    condition_2 = beats_always_flat and beats_other_baselines

    condition_3 = all(
        cell_agg[v]["worst_window_total_return"] > 0 for v in co_primary_venues
    )

    return {
        "is_survivor": condition_1 and condition_2 and condition_3,
        "condition_1": condition_1,
        "condition_2": condition_2,
        "condition_3": condition_3,
    }


def family_kill(results: dict, cell_ids: list) -> bool:
    """A family is dead iff NONE of its cells is a survivor (spec §6)."""
    return not any(results[c]["is_survivor"] for c in cell_ids)


def class_kill(results: dict) -> dict:
    """The whole 4h EUR/USD candidate class is dead iff EITHER (a) none of
    the 33 cells is a survivor, OR (b) every cell that clears the median
    criterion (conditions 1-2) nonetheless fails the worst-window criterion
    (condition 3) -- spec §6. (b) is a strict subset of "no survivor
    exists" (a survivor requires all three conditions), so the actual gate
    is simply "no survivor anywhere"; the two reasons below just
    sub-classify WHY for reporting -- (a) no cell even clears the median
    bar, vs (b) some do but none also survives its own worst window.

    Returns ``{"class_dead": bool, "reason": str | None}``.
    """
    if any(r["is_survivor"] for r in results.values()):
        return {"class_dead": False, "reason": None}

    clears_median = [
        cell_id for cell_id, r in results.items()
        if r["condition_1"] and r["condition_2"]
    ]
    if not clears_median:
        return {"class_dead": True, "reason": "a_no_cell_clears_median"}
    return {"class_dead": True, "reason": "b_never_survives_worst_window"}


# ---------------------------------------------------------------------------
# Synthetic smoke fixture (spec §7) -- code-generated, deterministic, NEVER
# real cache data. This is the ONLY execution input for
# ``run_fx_survey.py --smoke``.
# ---------------------------------------------------------------------------

_SMOKE_YEARS = 1.5
_SMOKE_HOURS = int(_SMOKE_YEARS * 365 * 24)
_SMOKE_START = "2020-01-01"


def make_smoke_fixture(*, seed: int = 42) -> pd.DataFrame:
    """~1.5 synthetic 'years' of H1-style bid/ask/mid OHLC rows -- a fixed-
    seed (``numpy.random.default_rng``, never real EUR/USD history) log-
    random-walk. CONTINUOUS 24/7 hourly bars (unlike the real FXCM archive,
    which closes on weekends) -- deliberate, so every Saturday in the
    fixture carries a full day of bars and the carve-out
    (``fx_data.drop_saturday_bars``) is exercised on every single run, not
    just "a few" injected rows.

    Same column shape as ``fx_data.parse_week_csv``'s output (Bid/Ask/Mid
    Open/High/Low/Close, tz-aware UTC ``datetime_utc`` index) so it can be
    fed directly into the SAME downstream pipeline steps
    (``drop_saturday_bars`` -> ``resample_to_4h`` -> ``drop_in_progress_bar``)
    ``prepare_history`` uses for real cache data -- this function itself
    never touches the cache or the network.
    """
    rng = np.random.default_rng(seed)
    idx = pd.date_range(_SMOKE_START, periods=_SMOKE_HOURS, freq="1h", tz="UTC")
    idx.name = "datetime_utc"

    log_rets = rng.normal(0.0, 0.0003, _SMOKE_HOURS)
    mid_close = 1.10 * np.exp(np.cumsum(log_rets))
    mid_open = np.empty_like(mid_close)
    mid_open[0] = mid_close[0]
    mid_open[1:] = mid_close[:-1]

    wiggle = rng.uniform(0.00002, 0.00008, _SMOKE_HOURS)
    mid_high = np.maximum(mid_open, mid_close) + wiggle
    mid_low = np.minimum(mid_open, mid_close) - wiggle

    half_spread = 0.00003  # ~0.6 pip round trip, a plausible EURUSD spread
    df = pd.DataFrame({
        "BidOpen": mid_open - half_spread, "BidHigh": mid_high - half_spread,
        "BidLow": mid_low - half_spread, "BidClose": mid_close - half_spread,
        "AskOpen": mid_open + half_spread, "AskHigh": mid_high + half_spread,
        "AskLow": mid_low + half_spread, "AskClose": mid_close + half_spread,
        "MidOpen": mid_open, "MidHigh": mid_high, "MidLow": mid_low, "MidClose": mid_close,
    }, index=idx)
    return df


def make_smoke_spy_fixture(*, seed: int = 43) -> pd.DataFrame:
    """Synthetic daily 'SPY' Open/Close frame (spec §7), fixed-seed, never
    real SPY history -- fed to ``compute_spy_windows`` via a monkeypatched
    ``fetch`` argument in smoke mode."""
    rng = np.random.default_rng(seed)
    n_days = int(_SMOKE_YEARS * 365)
    idx = pd.bdate_range(_SMOKE_START, periods=n_days)
    log_rets = rng.normal(0.0003, 0.01, n_days)
    close = 300.0 * np.exp(np.cumsum(log_rets))
    open_ = close * 0.999
    return pd.DataFrame({"Open": open_, "Close": close}, index=idx)


# ---------------------------------------------------------------------------
# Per-cell / per-baseline window runners (used by both stage 2c's real
# survey and this package's synthetic smoke run).
# ---------------------------------------------------------------------------

def _mid_ohlc_to_exec_bars(pre_rolled: pd.DataFrame) -> pd.DataFrame:
    return pre_rolled.rename(
        columns={"MidOpen": "Open", "MidHigh": "High", "MidLow": "Low", "MidClose": "Close"}
    )[["Open", "High", "Low", "Close"]]


def run_cell_across_windows(
    bars_4h: pd.DataFrame, signal_fn, r: float, windows: list, *,
    cost_rt: float, overnight, tax_mode: str, starting_equity: float = 100_000.0,
) -> dict:
    """Run one (shape, R, cost, tax-mode) candidate cell across every
    window, Trap-A-slicing metrics to each window's test sub-window only.

    Returns ``{"windows": [...], "summary": {...}}``:

    - ``windows``: one row PER window passed in, in order -- including
      windows with ``scored=False`` (e.g. ND1's excluded partial trailing
      year: still reported as unscored coverage, per spec §7's "results are
      reported, not discarded") and windows skipped for insufficient bars
      (``skipped=True``, ``skip_reason`` in {"insufficient_pre_roll_bars",
      "insufficient_test_bars"}, plus ``n_pre_roll_bars``/``n_test_bars``
      bar counts -- SUB_PLAN §5: "reported so 2c sees the vendor data
      holes instead of silently interpolating"). A non-skipped row carries
      every key in ``METRIC_KEYS`` plus the bar counts.
    - ``summary``: ``aggregate_metric_across_windows`` over the SCORED,
      non-skipped rows only (spec §5 walk-forward convention).
    """
    window_rows: list = []
    for w in windows:
        scored = w.get("scored", True)
        pre_rolled = bars_4h.loc[
            (bars_4h.index >= w["pre_roll_start"]) & (bars_4h.index < w["test_end"])
        ]
        n_pre_roll_bars = len(pre_rolled)
        if n_pre_roll_bars < 2:
            window_rows.append({
                "year": w["year"], "scored": scored, "skipped": True,
                "skip_reason": "insufficient_pre_roll_bars",
                "n_pre_roll_bars": n_pre_roll_bars, "n_test_bars": None,
            })
            continue

        entry_dir = signal_fn(pre_rolled)
        exec_bars = _mid_ohlc_to_exec_bars(pre_rolled)
        sim = fx_execution.simulate_fx(
            exec_bars, entry_dir, tp_pct=r, sl_pct=r, cost_rt=cost_rt,
            overnight=overnight, starting_equity=starting_equity,
        )
        eq_full = sim["equity_curve"]
        test_mask = (eq_full.index >= w["test_start"]) & (eq_full.index < w["test_end"])
        eq_test = eq_full.loc[test_mask]
        n_test_bars = len(eq_test)
        if n_test_bars < 2:
            window_rows.append({
                "year": w["year"], "scored": scored, "skipped": True,
                "skip_reason": "insufficient_test_bars",
                "n_pre_roll_bars": n_pre_roll_bars, "n_test_bars": n_test_bars,
            })
            continue

        test_trades = [
            t for t in sim["trades"]
            if t["exit_date"] >= w["test_start"] and t["exit_date"] < w["test_end"]
        ]
        after_tax = compute_after_tax_metrics(eq_test, test_trades, mode=tax_mode)
        window_rows.append({
            "year": w["year"], "scored": scored, "skipped": False, "skip_reason": None,
            "n_pre_roll_bars": n_pre_roll_bars, "n_test_bars": n_test_bars,
            **after_tax,
        })

    scored_rows = [
        row for row in window_rows if row["scored"] and not row["skipped"]
    ]
    return {"windows": window_rows, "summary": aggregate_metric_across_windows(scored_rows)}


_BASELINE_STATE_FNS = {
    "always_flat": lambda pre_rolled, w: fx_baselines.always_flat_state(pre_rolled.index),
    "buy_and_hold": lambda pre_rolled, w: fx_baselines.buy_and_hold_state(
        pre_rolled.index, w["pre_roll_start"],
    ),
    "persistence": lambda pre_rolled, w: fx_baselines.persistence_state(pre_rolled["MidClose"]),
    "sma200_regime": lambda pre_rolled, w: fx_baselines.sma200_regime_state(
        pre_rolled["MidClose"], n=200,
    ),
}


def run_baseline_across_windows(
    bars_4h: pd.DataFrame, baseline_key: str, windows: list, *,
    cost_rt: float, overnight, tax_mode: str, starting_equity: float = 100_000.0,
) -> dict:
    """Run one of the 4 dumb baselines (spec §5) across every window via
    ``fx_execution.simulate_fx_state`` (no TP/SL -- the candidate/baseline
    execution asymmetry). ``baseline_key`` in {"always_flat",
    "buy_and_hold", "persistence", "sma200_regime"}.

    Same ``{"windows": [...], "summary": {...}}`` return shape as
    ``run_cell_across_windows`` (full per-window rows incl. unscored/
    skipped, bar counts, a summary over the scored non-skipped rows).

    The baseline-4 (``sma200_regime``) degenerate-window convention (spec
    §6 -- a window entirely flat, zero trades, treated as return=0/calmar=0
    rather than left NaN) is applied ONLY when building the summary
    aggregate -- the raw per-window row in ``windows`` is left untouched
    (the true NaN calmar / zero trade_count), so a downstream consumer can
    always see what actually happened, not the convention's substitute.
    """
    if baseline_key not in _BASELINE_STATE_FNS:
        raise ValueError(f"unknown baseline_key {baseline_key!r}")
    state_fn = _BASELINE_STATE_FNS[baseline_key]

    window_rows: list = []
    for w in windows:
        scored = w.get("scored", True)
        pre_rolled = bars_4h.loc[
            (bars_4h.index >= w["pre_roll_start"]) & (bars_4h.index < w["test_end"])
        ]
        n_pre_roll_bars = len(pre_rolled)
        if n_pre_roll_bars < 2:
            window_rows.append({
                "year": w["year"], "scored": scored, "skipped": True,
                "skip_reason": "insufficient_pre_roll_bars",
                "n_pre_roll_bars": n_pre_roll_bars, "n_test_bars": None,
            })
            continue

        state = state_fn(pre_rolled, w)
        exec_bars = _mid_ohlc_to_exec_bars(pre_rolled)
        sim = fx_execution.simulate_fx_state(
            exec_bars, state, cost_rt=cost_rt, overnight=overnight, starting_equity=starting_equity,
        )
        eq_full = sim["equity_curve"]
        test_mask = (eq_full.index >= w["test_start"]) & (eq_full.index < w["test_end"])
        eq_test = eq_full.loc[test_mask]
        n_test_bars = len(eq_test)
        if n_test_bars < 2:
            window_rows.append({
                "year": w["year"], "scored": scored, "skipped": True,
                "skip_reason": "insufficient_test_bars",
                "n_pre_roll_bars": n_pre_roll_bars, "n_test_bars": n_test_bars,
            })
            continue

        test_trades = [
            t for t in sim["trades"]
            if t["exit_date"] >= w["test_start"] and t["exit_date"] < w["test_end"]
        ]
        after_tax = compute_after_tax_metrics(eq_test, test_trades, mode=tax_mode)
        window_rows.append({
            "year": w["year"], "scored": scored, "skipped": False, "skip_reason": None,
            "n_pre_roll_bars": n_pre_roll_bars, "n_test_bars": n_test_bars,
            **after_tax,
        })

    scored_rows = [
        row for row in window_rows if row["scored"] and not row["skipped"]
    ]
    if baseline_key == "sma200_regime":
        scored_rows = apply_baseline4_degenerate_convention(scored_rows)

    return {"windows": window_rows, "summary": aggregate_metric_across_windows(scored_rows)}


# ---------------------------------------------------------------------------
# run_survey -- the full combinatorial composition (SUB_PLAN should-fix #3),
# extracted as a parameterized, import-callable function: ALL 33 cells x
# the full cost matrix x both tax modes, 3 simulated dumb baselines +
# always-flat applied as the median-return>0 criterion, the SPY bar, and
# the §6 evaluator. Takes ALREADY-PREPARED ``bars_4h``/``windows`` -- it
# does no data loading of its own (no cache/network access whatsoever),
# so stage 2c can call it directly against real data (via
# ``prepare_history`` + ``slice_calendar_year_windows`` + a real
# ``spy_fetch``) with zero changes. The BLOCKED guard lives ONLY in the CLI
# (``run_fx_survey.py``); this function has no such guard and no full-
# history opinion of its own -- it just runs whatever it's given.
# ---------------------------------------------------------------------------

def run_survey(
    bars_4h: pd.DataFrame, windows: list, *, measured_spread_pips: float, spy_fetch,
) -> dict:
    """Run the entire survey composition over already-prepared ``bars_4h``
    and already-sliced ``windows``. Returns a dict digest (never prints --
    the CLI owns presentation):

    ``cell_full_matrix``: ``{cell_id: {"<venue>_<cost_mode>": {"<tax_mode>":
    {"windows": [...], "summary": {...}}}}}`` -- the FULL per-window +
    summary structure survives all the way through, for every one of the
    33 cells x 9 cost rows x 2 tax modes (must-fix #1).

    ``cell_co_primary_annual``, ``baseline_co_primary_annual``: the
    co-primary-venue, primary-tax-mode SUMMARY slices the §6 evaluator
    consumes (still nested under the venue key for symmetry with
    ``cell_full_matrix``).

    ``spy_median_calmar``, ``survivor_results``, ``family_kills``,
    ``class_kill``: as before.
    """
    costs = cost_rows(measured_spread_pips=measured_spread_pips)
    tax_modes = ("annual_netting", "de_sensitivity")

    cells = fx_signals.build_cells()
    cell_full_matrix: dict = {}
    cell_co_primary_annual: dict = {}
    for cell in cells:
        cid = cell["cell_id"]
        cell_full_matrix[cid] = {}
        for cost_row in costs:
            row_key = f"{cost_row['venue_key']}_{cost_row['cost_mode']}"
            cell_full_matrix[cid][row_key] = {}
            for tmode in tax_modes:
                cell_full_matrix[cid][row_key][tmode] = run_cell_across_windows(
                    bars_4h, cell["fn"], cell["r"], windows,
                    cost_rt=cost_row["cost_rt"], overnight=cost_row["overnight"], tax_mode=tmode,
                )
        cell_co_primary_annual[cid] = {
            "xtb_base": cell_full_matrix[cid]["xtb_base"]["annual_netting"]["summary"],
            "6e_base": cell_full_matrix[cid]["6e_base"]["annual_netting"]["summary"],
        }

    base_cost_by_venue = {
        c["venue_key"]: c for c in costs if c["cost_mode"] == "base" and c["venue_key"] in ("xtb", "6e")
    }
    baseline_full_matrix: dict = {}
    baseline_co_primary_annual: dict = {}
    for bname in ("buy_and_hold", "persistence", "sma200_regime"):
        baseline_full_matrix[bname] = {}
        baseline_co_primary_annual[bname] = {}
        for venue_key, cost_row in base_cost_by_venue.items():
            full = run_baseline_across_windows(
                bars_4h, bname, windows,
                cost_rt=cost_row["cost_rt"], overnight=cost_row["overnight"], tax_mode="annual_netting",
            )
            baseline_full_matrix[bname][f"{venue_key}_base"] = full
            baseline_co_primary_annual[bname][f"{venue_key}_base"] = full["summary"]

    spy_windows_metrics = compute_spy_windows(calendar_windows=windows, fetch=spy_fetch)
    spy_scored = [m for m in spy_windows_metrics if m.get("scored", True)]
    spy_agg = (
        aggregate_metric_across_windows(spy_scored) if spy_scored
        else {"median_calmar": float("nan")}
    )
    spy_median_calmar = spy_agg["median_calmar"]

    survivor_results = {
        cid: evaluate_survivor(
            cell_agg=cagg, baseline_aggs=baseline_co_primary_annual,
            spy_median_calmar=spy_median_calmar,
        )
        for cid, cagg in cell_co_primary_annual.items()
    }

    families = {
        "T": [c["cell_id"] for c in cells if c["shape_id"].startswith("T")],
        "M": [c["cell_id"] for c in cells if c["shape_id"].startswith("M")],
        "R": [c["cell_id"] for c in cells if c["shape_id"].startswith("R")],
    }
    family_kills = {fam: family_kill(survivor_results, ids) for fam, ids in families.items()}
    overall_class_kill = class_kill(survivor_results)

    return {
        "measured_spread_pips": measured_spread_pips,
        "windows": windows,
        "cell_full_matrix": cell_full_matrix,
        "cell_co_primary_annual": cell_co_primary_annual,
        "baseline_full_matrix": baseline_full_matrix,
        "baseline_co_primary_annual": baseline_co_primary_annual,
        "spy_median_calmar": spy_median_calmar,
        "survivor_results": survivor_results,
        "family_kills": family_kills,
        "class_kill": overall_class_kill,
    }


# ---------------------------------------------------------------------------
# Full smoke composition (spec §7) -- run_smoke_survey is a THIN wrapper:
# generate the synthetic fixture + windows, then delegate the entire
# combinatorial loop to run_survey. This is the ONLY runnable end-to-end
# path in this package; ``run_fx_survey.py --smoke`` calls this. NEVER
# touches ``fx_data.read_cache``/``get_week_bytes``.
# ---------------------------------------------------------------------------

def run_smoke_survey(*, seed: int = 42) -> dict:
    """Compose the entire survey on the code-generated synthetic fixture.
    Returns a dict digest; never prints (the CLI owns presentation)."""
    h1 = make_smoke_fixture(seed=seed)
    h1_no_saturdays, n_saturday_dropped = fx_data.drop_saturday_bars(h1)
    post_check = fx_data.check_weekend_bars(h1_no_saturdays)
    assert post_check["n_saturday_bars"] == 0

    bars_4h, resample_report = fx_data.resample_to_4h(h1_no_saturdays)
    bars_4h = fx_data.drop_in_progress_bar(bars_4h)

    measured_spread_pips = float(fx_data.empirical_spread_pips(h1_no_saturdays).median())

    first_test_year = bars_4h.index[0].year + 1
    windows = slice_calendar_year_windows(
        bars_4h.index, first_test_year=first_test_year,
        pre_roll_bars=DEFAULT_PRE_ROLL_BARS, excluded_years=(),
    )

    spy_frame = make_smoke_spy_fixture(seed=seed + 1)
    result = run_survey(
        bars_4h, windows, measured_spread_pips=measured_spread_pips,
        spy_fetch=lambda ticker, start, end: spy_frame,
    )

    result["n_saturday_dropped"] = n_saturday_dropped
    result["bars_4h_len"] = len(bars_4h)
    result["resample_report"] = resample_report
    return result
